azine_hybrid_auth:
  endpoint_route:       azine_hybrid_auth_endpoint # the route_name where your endpoint controller (e.g. HybridEndPointController) is available
  debug:                false # set to true to log debug-information to the debug_file
  debug_file:           '%kernel.logs_dir%/hybrid_auth_%kernel.environment%.log' # location of the debug-file
  store_for_user:       false # set to true to store hybrid auth session data into your database for the logged in user
  store_as_cookie:      false # set to true if session-information should be stored as cookies (e.g. for anon. users)
  providers:

    # Prototype (at least one provider has to be defined)
    steam:
      enabled:              true
      scope:                ~ # comma-separated list of required 'access rights'
      wrapper:
        path: "%kernel.root_dir%/../vendor/hybridauth/hybridauth/additional-providers/hybridauth-steam/Providers/Steam.php"
        class: Hybrid_Providers_Steam
      keys:
        key:                  '719D345AC63852491A7D565875E288F5'
        secret:               'zd9OO34CWU0fp3PycseVRegwqUvgiZ4J'
