fos_user:
  db_driver: orm
  firewall_name: main
  user_class: FOS\UserBundle\Model\User
  group:
    group_class: FOS\UserBundle\Model\Group
  from_email:
    address: "%mailer_user%"
    sender_name: "%mailer_user%"
