fos_rest:
  serializer:
    serialize_null: true
  param_fetcher_listener: force
  body_listener:          true
  routing_loader:
    default_format: json
    include_format: true
  view:
    formats:
      xml: true
      json : true
    view_response_listener: force
  body_converter:
    enabled: false
    validate: true
  format_listener:
    rules:
    - { path: ^/api, priorities: [ json,xml ], fallback_format: json, prefer_extension: true }
    - { path: ^/, priorities: [ html ], fallback_format: html, prefer_extension: true }
