fos_user:
  db_driver: orm
  firewall_name: admin
  user_class: App\Entity\User
  group:
    group_class: App\Entity\Group
  from_email:
    address: "%mailer_user%"
    sender_name: "%mailer_user%"

sonata_user:
  security_acl:     true
  class:
    user: App\Entity\User
    group: App\Entity\Group
  impersonating:
    route: sonata_admin_dashboard
