framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: null
    #http_method_override: true
    #trusted_hosts: null
    # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
    #esi: ~
    #fragments: ~
    assets: ~
    session: ~
    templating:
        engines: ["twig"]
    php_errors:
        log: true
