nelmio_api_doc:
    documentation:
        info:
            title: Cardinal Guild Island API
            description: API documentation for all things map related for Worlds Adrift
            version: 1.0.0
    areas: # to filter documented areas
        default:
            path_patterns: 
                - ^(/api(?!(/doc.*(\.json)?|/account.*)$)|/.*_log$)
        account:
            path_patterns:
                -  ^/api/account.*$
