sonata_admin:
    title: 'Cardinal Guild Surveyor'
    title_logo: /assets/logo_small.png
    dashboard:
        groups:
            island.management:
                label: Island Management
                icon:  '<i class="fa fa-globe"></i>'
                items:
                - admin.island
                - admin.island_creator
                - route:        reposition_islands
                  label:        "Reposition islands"
                  roles:        [ ROLE_SURVEYOR ]

            reporting:
                label: Reporting
                icon:  '<i class="fa fa-bug"></i>'
                items:
                - admin.report
                roles:        [ ROLE_SURVEYOR ]

            type.management:
                label: Type Management
                icon:  '<i class="fa fa-diamond"></i>'
                items:
                - admin.metaltype
                - admin.treetype
            territory.management:
                label: Territory Management
                icon:  '<i class="fa fa-compass"></i>'
                items:
                    - admin.alliance
                    - admin.tower
            sonata.admin.group.administration:
                label:           "User management"
                label_catalogue: SonataAdminBundle
                icon:            '<i class="fa fa-user"></i>'
                items:
                - sonata.user.admin.user
                - sonata.user.admin.group
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    security:
        handler: sonata.admin.security.handler.acl
        role_admin: ROLE_ADMIN
        role_super_admin: ROLE_SUPER_ADMIN
        information:
            READER:   [VIEW, LIST]
            GUEST:    [CREATE, VIEW, LIST]
            EDITOR:   [EDIT, VIEW, LIST, OPERATOR, EXPORT]
            ADMIN:    [MASTER]
        admin_permissions: [CREATE, EDIT, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]
sonata_block:
    blocks:
        sonata.admin.block.stats:
            contexts:   [admin]
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts:   [admin]
