vich_uploader:
    db_driver: orm
    mappings:
        island_image:
            uri_prefix: /images/islands
            upload_destination: '%kernel.project_dir%/public/images/islands'
            namer: Vich\UploaderBundle\Naming\HashNamer
            inject_on_load: false
            delete_on_remove:   true
            delete_on_update:   true
