version: '3.2'

services:
  traefik:
    container_name: traefik
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=traefik'
      - 'traefik.port=8080'
      - 'traefik.frontend.rule=Host:traefik.lc'

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: surveyor
      MYSQL_USER: surveyor
      MYSQL_PASSWORD: surveyor
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    labels:
      - 'traefik.backend=db'
      - 'traefik.port=3306'
      - 'traefik.frontend.rule=Host:db.surveyor.lc'

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.surveyor.lc'

  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
      - 'traefik.backend=pma'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:pma.surveyor.lc'

  devops:
    image: webdevops/php-nginx
    links:
      - db:db.surveyor.lc
      - mailhog:mailhog.surveyor.lc
      - redis:redis.surveyor.lc
    depends_on:
      - db
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_SAFE_MODE: 0
    volumes:
      - ./:/var/www/html:rw,cached
      - ./vhost.conf:/opt/docker/etc/nginx/vhost.conf:ro
    labels:
      - 'traefik.backend=devops'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:localhost,surveyor.lc'

  ngrok:
    image: wernight/ngrok
    depends_on:
      - devops
    links:
      - devops:http
    environment:
      NGROK_REGION: eu
    labels:
      - 'traefik.backend=ngrok'
      - 'traefik.port=4040'
      - 'traefik.frontend.rule=Host:ngrok.surveyor.lc'
    command: "ngrok http http:80"

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    labels:
      - 'traefik.backend=redis'
      - 'traefik.port=6379'
      - 'traefik.frontend.rule=Host:redis.surveyor.lc'
volumes:
  db: {}
