version: 2
jobs:
  build:
    docker:
    - image: buildpack-deps:trusty
    steps:
    - checkout
    - run:
        name: Deploy Master to surveyor.cardinalguild.com
        command: |
          ssh-keyscan alloy.creatiom.be >> ~/.ssh/known_hosts
          git config --global push.default simple
          git remote add deploy dokku@alloy.creatiom.be:surveyor
          git push deploy master

workflows:
  version: 2
  build-deploy:
    jobs:
    - build:
        filters:
          branches:
            only: master
