index:
    path: /
    defaults: { _controller: 'App\Controller\HomeController::welcome' }

steam_connect:
    path:   /connect
    controller: "AzineHybridAuthBundle:AzineHybridAuthJson:connectUser"
    defaults:
        provider: 'steam'
        callbackRoute: 'steam_callback'
# Depends on sensio/framework-extra-bundle, doctrine/annotations, and doctrine/cache
#   install with composer req sensio/framework-extra-bundle annot
#controllers:
#    resource: ../src/Controller/
#    type: annotation
