# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    mailer_user: 'jan@creatiom.be'

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../src/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    App\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']

    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
        - { name: doctrine.event_subscriber, connection: default }
        calls:
        - [ setAnnotationReader, [ '@annotation_reader' ] ]

    admin.island:
        class: App\Admin\IslandAdmin
        arguments: [~, App\Entity\Island, ~]
        tags:
        - { name: sonata.admin, manager_type: orm, group: "Island management", label: "Islands", icon: "<i class=\"fa fa-globe\"></i>" }
        public: true

    admin.treetype:
        class: App\Admin\TreeTypeAdmin
        arguments: [~, App\Entity\TreeType, ~]
        tags:
        - { name: sonata.admin, manager_type: orm, group: "Type management", label: "Trees", icon: "<i class=\"fa fa-diamond\"></i>" }
        public: true

    admin.metaltype:
        class: App\Admin\MetalTypeAdmin
        arguments: [~, App\Entity\MetalType, ~]
        tags:
        - { name: sonata.admin, manager_type: orm, group: "Type management", label: "Metals", icon: "<i class=\"fa fa-diamond\"></i>" }
        public: true
